export const channelsMap: Record<string, string> = {
  NTVM: 'НТВ',
  TVCREGION: 'ТВ Центр',
  ROSSIA1: 'Россия 1',
  '1TVM': 'Первый канал',
  TNT: 'ТНТ',
  MATCHTV: 'Матч ТВ',
  ROSSIAK: 'Россия К',
  TNT4: 'ТНТ4',
  SPBTV: 'Пятый канал',
  RENTV: 'РЕН ТВ',
  DOMASHNY: 'Домашний',
  STS: 'СТС',
  KARUSEL: 'Карусель',
  SPAS: 'Спас',
  CHE: 'Че',
  '2X2': '2x2',
  DISNEY: 'Disney',
  TV3: 'ТВ-3',
  ZVEZDA: 'Звезда',
  OTR: 'ОТР',
  PYATNITSA: 'Пятница!',
  MUZTV: 'Муз ТВ',
  UTV: 'ЮТВ',
};
